name: Tweetbot TYPO3Gratitude

on:
  push:
    branches:
      - "**"
    #  schedule:
    #   - cron: "*/15 * * * *"

env:
  TWEETBOT_TYPO3GRATITUDE_SETTINGS: ${{ secrets.TWEETBOT_TYPO3GRATITUDE_SETTINGS }}

jobs:
  tweet:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Get tweetbot
        run: wget https://github.com/tomasnorre/twitter-bot/releases/download/v0.0.1/tweetbot

      - name: Write Config file
        run: echo "${{ env.TWEETBOT_TYPO3GRATITUDE_SETTINGS }}" > settings.yaml

      - name: Get lastTweetId
        uses: actions/download-artifact@v2
        with:
          name: lastTweetIdTYPO3Gratitude

      - name: Tweet
        run: chmod +x tweetbot && ./tweetbot

      - name: Upload lastTweetId
        uses: actions/upload-artifact@v2
        with:
          name: lastTweetIdTYPO3Gratitude
          path: lastTweetId